### ISSUE TITLE
add support for context types

### ISSUE THREAD

**Issue by jankuca** [brigand/babel-plugin-flow-react-proptypes#61] opened 2016-12-15 13:58 UTC
The logic should be pretty much the same I guess and this would make this plugin actually really useful.

Prop flow type to `propTypes` conversion is not actually that vital since the lack of `propTypes` does not render components unusable whereas `contextTypes` must be generated for the components to work correctly.

What are your thoughts on this?

**Comment by brigand** [comment] 2016-12-15 14:48
Duplicate of https://github.com/brigand/babel-plugin-flow-react-proptypes/issues/22

**Closed by brigand** 2016-12-15 14:48 UTC
