### ISSUE TITLE
Context types

### ISSUE THREAD

**Issue by BLamy** [brigand/babel-plugin-flow-react-proptypes#63] opened 2017-01-06 18:16 UTC
Are there any plans to also support Context types?

Currently things need to be done as such:
```ts
type User = { id: number, name: string }
type Props = { id: number }
type State = { user: User }
export default class UserSmartComponent extends Component {
  props: Props
  state: State = { user: {} }
  static contextTypes = { socket: PropTypes.object.isRequired }

  componentDidMount() {
     this.context.socket.getUser(this.props.id).then(user => this.setState({ user }))
  }

  render() {
    return <h1>this.state.user.name</h1>
  }
}
```

I'd prefer to see something like this:

```ts
type User = { id: number, name: string }
type Props = { id: number }
type State = { user: User }
type Context = { socket: Object }
export default class UserSmartComponent extends Component {
  props: Props
  state: State = { user: {} }
  context: Context

  componentDidMount() {
     this.context.socket.getUser(this.props.id).then(user => this.setState({ user }))
  }

  render() {
    return <h1>this.state.user.name</h1>
  }
}
```

**Comment by brigand** [comment] 2017-01-07 00:12
Duplicate of https://github.com/brigand/babel-plugin-flow-react-proptypes/issues/22

This has come up enough times that it's worth considering. I'd accept a PR if it's put behind a config option, disabled by default.

**Comment by mhaas** [comment] 2017-06-03 08:42
This shouldn't be too hard.

To understand the additional annotations:

For functional components, we should check if a second parameter to the function exists in `getFunctionalComponentTypeProps()`. For proper component classes, we need to add a check for 'context' along the existing check on 'props' around line 190 in index.js. The `convertNodeToPropTypes` function should stay the same.

To generate the proper code:

We need to change/extend the `annotate` function in index.js to attach the context propTypes to `.contextTypes` in addition to the current support for `propTypes`.

Not sure if I will have the time to work on this, just putting it out there..

**Closed** 2017-12-11 22:17 UTC
