### ISSUE TITLE
Option to silence/disable warnings [Feature request]

### ISSUE THREAD

**Issue by IanVS** [brigand/babel-plugin-flow-react-proptypes#181] opened 2018-02-16 22:43 UTC
Hi, would you consider adding an option to run in `silent` mode, meaning that warnings are not shown?  I'm getting a lot of warnings about not finding proptypes from `react-router-dom`, but those are all flow types being used as flow types and not proptypes, so I don't really care about the warnings.  Thanks!

**Comment by brigand** [comment] 2018-02-16 23:04
Could you copy/paste the warning you're getting and the code causing it? I don't know what you're referring to.

**Comment by IanVS** [comment] 2018-02-17 01:52
Hi, sure, the warnings I see are something like this:

```
[0] WARNING in ./path/to/my/file.js
[0] 26:24-53 "export 'bpfrpt_proptype_ContextRouter' was not found in 'react-router-dom'
[0]
[0] WARNING in ./path/to/my/file.js
[0] 26:79-108 "export 'bpfrpt_proptype_ContextRouter' was not found in 'react-router-dom'
```

And my code looks like:

```js
/* @flow */
import React, {PureComponent} from 'react';
import type {ContextRouter} from 'react-router-dom';

type Props = ContextRouter;

export class MyComponent extends PureComponent {
    props: ContextRouter;

    render() {
        return <div />;
    }
}
```

Let me know what else would be useful information.

**Comment by brigand** [comment] 2018-02-17 09:28
@IanVS you can add `'no babel-plugin-flow-react-proptypes';` to this file (with the quotes, like `'use strict'`).

This is webpack giving a warning, and it seems to be because `react-router-dom` is published as an ES6 module. Maybe we should check if the import line is non-relative, and if so, skip importing the type.

**Comment by IanVS** [comment] 2018-02-19 13:19
Hm, okay using the ignore directive is a bit unfortunate because I have a lot of files like this, but that's what I'll do for now.  I take it you don't really want to add a `silent` option, right?  If not, feel free to say so and close the issue.  I know that adding options isn't simple and comes with costs, so I'll understand if you don't want to add one.

**Comment by brigand** [comment] 2018-02-19 16:18
@IanVS the issue is that we're not giving the warning. For your code sample, we generate this code:

```js
import React, { PureComponent } from "react";

export class MyComponent extends PureComponent {
  render() {
    return React.createElement("div", null);
  }
}
MyComponent.propTypes =
  bpfrpt_proptype_ContextRouter === PropTypes.any
    ? {}
    : bpfrpt_proptype_ContextRouter;
import { bpfrpt_proptype_ContextRouter } from "react-router-dom";
import PropTypes from "prop-types";
```

Since the file `react-router-dom` resolves to is an ES6 module, and doesn't have an export with that name, webpack issues a warning.

The obvious solution is to check the specified import like, `/^\w/.test('react-router-dom')`, however that breaks code adding a 'module directory' or alias, e.g. `import X from 'src/foo/bar'`, so it's not a perfect solution. I think this is good enough though.

**Comment by FDiskas** [comment] 2018-03-13 14:00
updating to v21 solved this issue for me :camel:

**Comment by brigand** [comment] 2018-03-16 16:06
Yeah, should be fixed. Please open another issue if there are further issues.

**Closed by brigand** 2018-03-16 16:06 UTC
